extends Node2D
#[1,  """\
#XXXXEXXXX
#.........
#.........
#.........
#.........
#.........
#.........
#.........
#.........
#....P...."""]

@onready var game: Game = $Game
var levels: Array = [
[1,  """\
XXXXEXXXX
.........
.........
....X....
....W....
.........
....X....
.........
.........
....P...."""],
[1,  """\
XXXXEXXXX
...X.X...
...X.X...
...X.X...
...X.X...
...W.W...
...X.X...
...X.X...
...X.X...
...XPX..."""],
]

var current_level := 0
var final_level := len(levels) - 1

# Called when the node enters the scene tree for the first time.
func _ready():
	game.load_level(levels[0])

func _on_game_level_completed():
	if current_level == final_level:
		# TODO: load end game scene
		return
	
	current_level += 1
	game.load_level(levels[current_level])
